apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-example-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphql-example
  template:
    metadata:
      labels:
        app: graphql-example
    spec:
      containers:
      - name: graphql-example
        image: minusd/graphql-example:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres-service:5433/tinkoff_k8s_demo"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "root"
---
apiVersion: v1
kind: Service
metadata:
  name: graphql-example-service
spec:
  type: NodePort
  selector:
    app: graphql-example
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
